sudo: false
language: python
install:
    - pip install tox

script:
    - tox -e $TOXENV

matrix:
  fast_finish: true
  include:
    # Python version is just for the look on travis.
    - python: 2.7
      env: TOXENV=py27

    - python: 3.4
      env: TOXENV=py34

    - python: 3.5
      env: TOXENV=py35

    - python: 3.6
      env: TOXENV=py36

    - python: 3.7
      env: TOXENV=py37
      # As of September 2018, Python 3.7.0 is not available on "vanilla" travis builds.
      dist: xenial
      sudo: true

    # Lints and others
    - python: 3.6
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=py27-cov
    - python: 3.6
      env: TOXENV=py36-cov
